### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by Derpolino** [OllieTerrance/SkPy#29]
Hi ! Sorry for my bad english

```
Traceback (most recent call last):
  File "H:\Desktop\Mes_codes\Python\Skpy script\skype_pic2html.py", line 29, in <module>
    sk = MySkype("XXX", "XXX", autoAck=True)
  File "C:\Python27\lib\site-packages\skpy\main.py", line 189, in __init__
    super(SkypeEventLoop, self).__init__(user, pwd, msEmail, msPwd, tokenFile)
  File "C:\Python27\lib\site-packages\skpy\main.py", line 65, in __init__
    self.conn.getSkypeToken()
  File "C:\Python27\lib\site-packages\skpy\conn.py", line 261, in getSkypeToken
    self.liveLogin(user, pwd)
  File "C:\Python27\lib\site-packages\skpy\conn.py", line 378, in liveLogin
    data={"t": tField.get("value"), "client_id": "578134", "oauthPartner": "999",
AttributeError: 'NoneType' object has no attribute 'get'
```

When : 
`sk = MySkype("XXX", "XXX", autoAck=True)`

it's worked before, any idea please ? thanks !

EDIT : Btw : 

```
>pip install skpy --upgrade
Requirement already up-to-date: skpy in c:\python27\lib\site-packages
```

**Comment by OllieTerrance** [comment]
Looks like you're missing the `t` value after logging in.  This sometimes happens if your username/password are correct but the account is blocked for some reason (requires a captcha, accept new terms, or hit an auth limit).  First step: check you can login in a browser, on the same IP address, at https://web.skype.com.

If that looks good, start Python with `SKPY_DEBUG_HTTP=1` in the environment, which will output the HTTP requests.  Get a copy of the auth HTTP requests, specifically the one just before the exception happens, blank out any personal info, and attach it here.

(P.S. Your password was included in the stack trace above -- I've cut it out already, but best change your password in case anyone else has seen it!)

**Comment by leondealmeida** [comment]
@OllieTerrance, do you have a list of what those (somewhat?) known errors are? I'd be happy creating a pull request to provide more descriptive error messages.

**Comment by OllieTerrance** [comment]
Looking at the existing [`liveLogin()`](https://github.com/OllieTerrance/SkPy/blob/8fd42e0/skpy/conn.py#L338-L395) code, possible failures are:
* `PPFT` missing from 1st request (this is before providing a username/password, so may occur if Skype or Microsoft auth are down?)
* `t` missing from 2nd request (could be anything wrong with the account -- incorrect password, 2FA<sup>1</sup>, captchas, account locked, terms confirmation required)
* `skypetoken` missing from 3rd request (shouldn't be the user's fault at this point -- maybe downtime again?)

It's tricky to show a sensible error, though it would definitely be an improvement to throw a [`SkypeAuthException`](https://skpy.t.allofti.me/internal.html#skpy.conn.SkypeAuthException) instead of something like `AttributeError`.  This should be carefully tied down to avoid masking any possible non-auth exceptions...

---

<sup>1</sup> There's existing handling for detecting 2FA, though not sure if it's accurate -- pretty sure I've seen it show up for other reasons...

**Comment by OllieTerrance** [comment]
@Derpolino: A closer look at your stack trace suggests `tField` is `None`, but there's already [some handling to avoid this](https://github.com/OllieTerrance/SkPy/blob/8fd42e0/skpy/conn.py#L368), which is curious...  🤔

**Comment by leondealmeida** [comment]
@OllieTerrance, `tField` being `None` does allow processing to continue in case there is no error message in the response text. I've added a specific raise to that scenario on the commits referenced above - will create the PR now.

**Comment by OllieTerrance** [comment]
@Derpolino: Is this still a problem?

**Comment by OllieTerrance** [comment]
Can't reproduce... 😞
