### ISSUE TITLE
Retrieving a contact's presence ?

### ISSUE THREAD

**Issue by TrakJohnson** [OllieTerrance/SkPy#39]
I managed to retrieve a `skpy.user.SkypeContact`, however I have looked into this object's attributes in the docs and I can't find a way to get the contact's presence (online, ...).

Using the event system, I sometimes receive `SkypeEndpointsEvents` that indicate the presence of an active contact, but is there a way to get it for any contact even if they are inactive ?

**Comment by OllieTerrance** [comment]
There's no presence info available in the main APIs, you'll have to use the event stream.

An endpoint represents one connection for that contact (be that desktop, mobile, web etc.).  A contact with no active endpoints is not connected via any means, and is therefore offline.  As such, you'll probably need to work with the assumption that contacts are offline until told otherwise.

Additional pitfall: some clients (endpoints with push notifications, like mobile) use a form of extended away, and will always appear "connected" even if not...

**Comment by TrakJohnson** [comment]
Thanks, I didn't notice that the endpoints showed all the users' status at the beginning, I thought that it only recorded presence change after `sk.loop()`. 

If you don't mind (and that this is the right place to ask for this), I have also been struggling with detecting from who a message comes from: I can capture `SkypeMessageEvent`s, but how do I get the characteristics using the `msgId` ? I couldn't find any method that took it as an argument and returned date, user, conversation, etc...  How can I use these ids ?

**Comment by OllieTerrance** [comment]
You're looking for the [`msg`](https://skpy.t.allofti.me/api.html#skpy.event.SkypeMessageEvent.msg) attribute, which is a [`SkypeMsg`](https://skpy.t.allofti.me/api.html#skpy.msg.SkypeMsg) object containing the interesting details.

**Comment by TrakJohnson** [comment]
Thank you very much for the very rapid response, that's exactly what I'm looking for !
