### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by Lrcezimbra** [OllieTerrance/SkPy#77]
The project doesn't have a license, it would be interesting to add one

**Comment by OllieTerrance** [comment]
Interesting in what way?  Have you a suggestion for a particular license?

**Comment by Lrcezimbra** [comment]
For let us know how we can use the project. Without a license we can just view and fork the code, but can't use or modify it.

> If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose.

https://choosealicense.com/no-permission/

I usually use GPL or MIT, maybe is a good choice.
You can read more about licenses in https://choosealicense.com/.

**Comment by hosford42** [comment]
Please do add a license! I know it seems like a trivial thing, but it really is a show stopper for those of us downstream. This package looks very nice, and I want to add it as a dependency to a project of my own, but I will have to fall back on a less well-crafted package unless I can be sure I'm not violating copyright law by using this one.

My personal preference is for an unrestrictive license like MIT or BSD, which is basically just making it official that the code can be used as though it is in the public domain. If you prefer to go with a copyleft license instead, I would suggest you use LGPL rather than GPL, as it was designed with reusable libraries specifically in mind.

**Comment by OllieTerrance** [comment]
I'm currently leaning towards BSD as it includes a clearer line on redistribution of attribution, as opposed to MIT where it's slghtly hazy with "substantial portions".  As I understand it, the GPLs tend to be a pain for compatibility with other licenses in downstream projects...

**Comment by OllieTerrance** [comment]
As there haven't been any more comments either way, I've gone ahead and added a BSD 3-clause license to the library.  Hopefully this will give sufficient flexibility with your own projects' licensing.  🙂
